<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>. . : : || I S S U E || : : . .</title>
<link href="<?php echo Conectar::ruta();?>css/estilos.css" type="text/css" rel="stylesheet"/>
</head>
<body onload="document.form.reset();document.form.nombre.focus();">
<center>
<div id="principal">
    <div id="header">
        <?php include("header.phtml"); ?>
    </div>
    <div id="contenedor_medio">
        <?php
        if(isset($_SESSION["privilegio"]) and $_SESSION["privilegio"] == 'usuario')
        {
            include("menu_usuario.phtml");
        }
        else if(isset($_SESSION["privilegio"]) and $_SESSION["privilegio"] == 'administrador')
        {
            include("menu_admin.phtml");
        }
        ?>
        <br>
        <h2>Editar Perfil</h2>
        <?php
        if(isset($_GET["m"]))
        {
            switch($_GET["m"])
            {
                case '1':
                ?>
                <h2 style="color:red;"> Usted no relleno los campos nombre o login </h2>
                <?php
                break;

                case '2':
                ?>
                <h2 style="color:green;"> El perfil fue editado con éxito </h2>
                <?php
                break;

                case '3':
                ?>
                <h2 style="color:red;"> Login de usuario ya existe, vuelva a intentar </h2>
                <?php
                break;
            }
        }
        ?>
        <form name="form" action="" method="post">
		<span style="font-size:16px">
        <table align="center" width="400">
        <tr>
        <td valign="middle" align="center" colspan="2" width="400">
        <hr />
        </td>
        </tr>

        <tr style="background-color:#FCAE4F">
        <td valign="middle" align="right" width="200">
        <strong>Nombre:</strong>
        </td>
        <td valign="middle" align="left" width="200">
        <input type="text" name="nombre" size ="30" value="<?php echo $perfil[0]["nombre_usuario"];?>"/>
        </td>
        </tr>

        <tr style="background-color:#FCAE4F">
        <td valign="middle" align="right" width="200">
        <strong>Login:</strong>
        </td>
        <td valign="middle" align="left" width="200">
        <input type="text" name="login" size ="30" value="<?php echo $perfil[0]["login"];?>"/>
        </td>
        </tr>

        <tr>
        <td valign="middle" align="center" colspan="2" width="400">
        <hr />
        <input type="hidden" name="grabar" value="si" />
        <input type="hidden" name="id_usuario" value="<?php echo $_GET["id_usuario"]?>" />
        <input type="button" value="Editar Perfil" title="Editar Perfil" onclick="document.form.submit();" />
        </td>
        </tr>
        </table>
        </span>
        </form>
    </div>  <!--Fin div contenedor_medio-->
    <div id="reloj">
        <?php include("reloj.phtml"); ?>
    </div>
    <div id="sidebar">
        <?php include("perfilgral.phtml"); ?>
    </div>
    <div id="footer">
    <hr />
    &copy; Universidad Mayor de San Sim&oacuten - Entornos Virtuales  - <?php echo date("Y");?>
    </div>
</div> <!--Fin div Principal-->
</center>
</body>
</html>
