<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>::| Error |::</title>
</head>

<body>
<?php echo "Error Controller"; ?> <!--Error por q la variable accion no existe-->
<br />
<a href="<?php echo Conectar::ruta();?>?accion=index" title="Volver">Volver</a>
</body>
</html>