<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>. . : : || I S S U E || : : . .</title>
<link href="<?php echo Conectar::ruta();?>css/estilos.css" type="text/css" rel="stylesheet"/>
<link rel="stylesheet" type="text/css" href="<?php echo Conectar::ruta();?>css/tooltipster.css" />
<link rel="stylesheet" type="text/css" href="<?php echo Conectar::ruta();?>css/style2.css" />
<script language="javascript" type="text/javascript" src="<?php echo Conectar::ruta();?>js/md5.js"></script>
<script language="javascript" type="text/javascript" src="<?php echo Conectar::ruta();?>js/funciones.js"></script>
<script type="text/javascript" src="<?php echo Conectar::ruta();?>js/jquery-2.0.0.min.js"></script>
<script type="text/javascript" src="<?php echo Conectar::ruta();?>js/jquery.tooltipster.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $('.tooltip').tooltipster();
    });
</script>
</head>
<body onload="document.form.reset();document.form.login.focus();">
<center>
<div id="principal">
    <div id="header">
        <?php include("header_audio.phtml"); ?>
    </div>
    <div id="contenedor_medio">
        <?php include("menu_principal.phtml"); ?>
        <form name="form" action="" method="post">
        <?php
        if(isset($_GET["m"]))
        {
            switch($_GET["m"])
            {
                case '1':
                ?>
                <h2 style="color:red;">Los datos están vacíos</h2>
                <?php
                break;

                case '2':
                ?>
                <h2 style="color:red;">Los datos son incorrectos, intente de nuevo porfavor ! </h2>
                <?php
                break;

                case '3':
                ?>
                <h2 style="color:green;">Usted ha cerrado su sesión exitosamente </h2>
                <?php
                break;

                case '4':
                ?>
                <h2 style="color:red;"> Debe Loguearse primero para acceder a este contenido. </h2>
                <?php
                break;

                case '5':
                ?>
                <h2 style="color:red;"> Usted esta deshabilitado de ISSUE. </h2>
                <?php
                break;
            }
        }
        ?>
        <table align="center" width="400">
        <br /><br />
        <tr>
        <td valign="middle" align="center" colspan="2" width="400" style="font-size:24px">
        <strong>Ingrese sus Datos</strong>
        <hr />
        </td>
        </tr>

        <tr style="background-color:#FCAE4F">
        <td valign="middle" align="right" width="200">
        <b>Login:</b>
        </td>
        <td valign="middle" align="left" width="200">
        <input type="text" name="login" />
        </td>
        </tr>

        <tr style="background-color:#FCAE4F">
        <td valign="middle" align="right" width="200">
        <b>Password:</b>
        </td>
        <td valign="middle" align="left" width="200">
        <input type="password" name="pass" />
        </td>
        </tr>

        <tr>
        <td valign="middle" align="center" colspan="2" width="400">
        <hr />
        <input type="hidden" name="grabar" value="si" />
        <input type="button" value="Entrar" title="Entrar" onclick="validar_logueo();" />
        <br>
        <a href="<?php echo Conectar::ruta();?>?accion=registro" title="Registrate en ISSUE"><img src="images/registrate.png" border="0"></a>
        </td>
        </tr>
        </table>
        </form>
    </div>  <!--Fin div contenedor_medio-->
    <div id="reloj">
        <?php include("reloj.phtml"); ?>
    </div>
    <div id="sidebar">
        <?php include("social.phtml"); ?>
    </div>
    <div id="footer">
    <hr />
    &copy; Universidad Mayor de San Sim&oacuten - Entornos Virtuales  - <?php echo date("Y");?>
    </div>
</div> <!--Fin div Principal-->
</center>
</body>
</html>