<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>. . : : || I S S U E || : : . .</title>
<link href="<?php echo Conectar::ruta();?>css/estilos.css" type="text/css" rel="stylesheet"/>
<script language="javascript" type="text/javascript" src="<?php echo Conectar::ruta();?>js/funciones.js"></script>
</head>
<body>
<center>
<div id="principal">
    <div id="header">
        <?php include("header.phtml"); ?>
    </div>
    <div id="contenedor_medio">
        <?php
        include("menu_usuario.phtml");
        if(isset($_GET["m"]))
        {
            switch($_GET["m"])
            {
                case '1':
                ?>
                <h2 style="color: green">Se eliminó el registro exitosamente</h2>
                <?php
                break;

                case '2':
                ?>
                <h2 style="color: red">Se intentó eliminar el registro de forma errónea</h2>
                <?php
                break;
            }
        }
	    ?>
        <h2>Mis Archivos</h2>
       	<div id="contenedor_mis_archivos">
        <div class="barra_deslizante_mis_archivos">
        <?php
        if(empty($archivo))
        {
        ?>
            <h2 style="color:white;"> Usuario aún no tiene archivos cargados </h2>
        <?php
        }
        else
        {
        $inc=1;
        $sql=0;
        do {
            ?>
            <table align="center" width="805">

            <tr style="background-color:#FFCC33; color:#000000; font-weight:bold">

            <td valign="middle" align="center" width="25" height="30"  >
            Nro</td>

            <td valign="middle" align="center" width="200" height="30" >
            Titulo</td>

            <td valign="middle" align="center" width="200" height="30">
            Categoria</td>

            <td valign="middle" align="center" width="100" height="30">
            Fecha Ingreso</td>

            <td valign="middle" align="center" width="50" height="30">
            Editar Detalles</td>

            <td valign="middle" align="center" width="50" height="30">
            Volver a subir</td>

            <td valign="middle" align="center" width="50" height="30">
            Eliminar</td>
            </tr>
            <?php
            for($i=0;$i<count($archivo);$i++)
            {
            ?>

                <tr id="<?php echo "tr_$i";?>" style="background-color:#f0f0f0" onMouseMove="tr('<?php echo "tr_$i";?>','#cccccc');" onMouseOut="tr('<?php echo "tr_$i";?>','#f0f0f0');">

                <td valign="middle" align="center" height="30">
                <?php
                echo $inc++;
                ?></td>

                <td valign="middle" align="center" height="30">
                <?php
                echo $archivo[$i]["titulo"];
                ?></td>


                <td valign="middle" align="center" height="30">
                <?php
                echo $archivo[$i]["categoria"];
                ?>
                </td>

                <td valign="middle" align="center" height="30">
                <?php
                echo $archivo[$i]["fecha_archivo"];
                ?>
                </td>

                <td valign="middle" align="center" height="30">
                <a href="<?php echo Conectar::ruta();?>?accion=editarchivo&id_archivo=<?php echo $archivo[$i]["id_archivo"];?>" title="Editar detalles de <?php echo $archivo[$i]["titulo"];?>"><img src="<?php echo Conectar::ruta();?>images/editar.png" border="0" width="32" height="32" /></a>
                </td>


                <td valign="middle" align="center" height="30">
                <a href="<?php echo Conectar::ruta();?>?accion=volverasubir&id_archivo=<?php echo $archivo[$i]["id_archivo"];?>" title="Vuelva a subir otro archivo"><img src="<?php echo Conectar::ruta();?>images/volver.png" border="0" width="32" height="32" /></a>
                </td>


                <td valign="middle" align="center" height="30">
                <a href="#" title="Eliminar <?php echo $archivo[$i]["titulo"];?>" onclick="eliminar('<?php echo Conectar::ruta();?>?accion=deletearchivo&id_archivo=<?php echo $archivo[$i]["id_archivo"];?>')"><img src="<?php echo Conectar::ruta();?>images/eliminar.png" border="0" width="32" height="32" /></a>
                </td>
                </tr>
            <?php
            }
            ?>
            </table>
            <?php
            } while($sql);
        }
        ?>
        </div><!--Fin class barra_deslizante_mis_archivos-->
        </div> <!--fin contenedor_mis_archivos-->
    </div>  <!--Fin div contenedor_medio-->
    <div id="reloj">
        <?php include("reloj.phtml"); ?>
    </div>
    <div id="sidebar">
        <?php include("perfilgral.phtml"); ?>
    </div>
    <div id="footer">
    <hr />
    &copy; Universidad Mayor de San Sim&oacuten - Entornos Virtuales  - <?php echo date("Y");?>
    </div>
</div> <!--Fin div Principal-->
</center>
</body>
</html>