<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>. . : : || I S S U E || : : . .</title>
<link href="<?php echo Conectar::ruta();?>css/estilos.css" type="text/css" rel="stylesheet"/>
</head>
<body>
<center>
<div id="principal">
    <div id="header">
        <?php include("header.phtml"); ?>
    </div>
    <div id="contenedor_medio">
        <?php
        if(isset($_SESSION["privilegio"]) and $_SESSION["privilegio"] == 'usuario')
        {
            include("menu_usuario.phtml");
        }
        else if(isset($_SESSION["privilegio"]) and $_SESSION["privilegio"] == 'administrador')
        {
            include("menu_admin.phtml");
        }
        ?>
        <br>
        <h2>Perfil de usuario</h2>
	    <?php
        if(isset($_GET["m"]))
        {
            switch($_GET["m"])
            {
                case '1':
                ?>
                <h2 style="color:red;"> Codigo de usuario incorrecto </h2>
                <?php
                break;
            }
        }
        ?>
		<span style="font-size:16px">
        <table align="center" width="500">
        <tr>
        <td valign="middle" align="center" colspan="2" width="500">
        <hr />
        </td>
        </tr>

        <tr style="background-color:#FCAE4F">
        <td valign="middle" align="right" width="250">
        <strong>Nombre:</strong>
        </td>
        <td valign="middle" align="left" width="250">
        <?php echo $perfil[0]["nombre_usuario"];?>
        </td>
        </tr>

        <tr style="background-color:#FCAE4F">
        <td valign="middle" align="right" width="250">
        <strong>Login:</strong>
        </td>
        <td valign="middle" align="left" width="250">
        <?php echo $perfil[0]["login"];?>
        </td>
        </tr>

        <tr style="background-color:#FCAE4F">
        <td valign="middle" align="right" width="250">
        <strong>Estado:</strong>
        </td>
        <td valign="middle" align="left" width="250">
        <?php echo $perfil[0]["estado"];?>
        </td>
        </tr>

        <tr>
        <td valign="middle" align="center" colspan="2" width="400">
        <hr />
        </td>
        </tr>
        </table>
        </span>
        <br>
        <a href="<?php echo Conectar::ruta();?>?accion=editperfil&id_usuario=<?php echo $perfil[0]["id_usuario"];?>" title="Editar perfil de <?php echo $perfil[0]["nombre_usuario"];?>"><img src="<?php echo Conectar::ruta();?>images/edit_perfil.png" border="0" width="48" height="48" /></a>
                     &nbsp &nbsp &nbsp
        <a href="<?php echo Conectar::ruta();?>?accion=cambiarpass&id_usuario=<?php echo $perfil[0]["id_usuario"];?>" title="Cambiar password de <?php echo $perfil[0]["nombre_usuario"];?>"><img src="<?php echo Conectar::ruta();?>images/cambiar_pass.png" border="0" width="48" height="48" /></a>
                     &nbsp &nbsp &nbsp
        <a href="<?php echo Conectar::ruta();?>?accion=cambiarfoto&id_usuario=<?php echo $perfil[0]["id_usuario"];?>" title="Cambiar foto de perfil de <?php echo $perfil[0]["nombre_usuario"];?>"><img src="<?php echo Conectar::ruta();?>images/cambiar_foto.png" border="0" width="48" height="48" /></a>
    </div>  <!--Fin div contenedor_medio-->
    <div id="reloj">
        <?php include("reloj.phtml"); ?>
    </div>

    <div id="sidebar">
        <?php include("perfilgral.phtml"); ?>
    </div>
    <div id="footer">
    <hr />
    &copy; Universidad Mayor de San Sim&oacuten - Entornos Virtuales  - <?php echo date("Y");?>
    </div>
</div> <!--Fin div Principal-->
</center>
</body>
</html>