<br><br>
<section id="facebook">
<ul>
<a href="http://www.facebook.com" target="_blank"><span id="fackbook" class="tooltip" title="ISSUE en Facebook">FACEBOOK</span></a>
</ul>
</section>
<br><br><br><br>
<section id="twitter">
<ul>
<a href="http://www.twitter.com" target="_blank"><span id="twitter-default" class="tooltip" title="Siguenos en Twitter">TWITTER</span></a>
</ul>
</section>
<br><br><br><br>

<section id="google">
<ul>
<a href="https://plus.google.com" target="_blank"><span id="google-default" class="tooltip" title="Siguenos en Google Plus">Google +</span></a>
</ul>
</section>