<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>. . : : || I S S U E || : : . .</title>
<link href="<?php echo Conectar::ruta();?>css/estilos.css" type="text/css" rel="stylesheet"/>
</head>
<body onload="document.form.reset();document.form.titulo.focus();">
<center>
<div id="principal">
    <div id="header">
        <?php include("header.phtml"); ?>
    </div>
    <div id="contenedor_medio">
        <?php include("menu_usuario.phtml"); ?>
        <h2>Sube tu archivo</h2>
        <form name="form" action="" method="post" enctype="multipart/form-data">
        <?php
        if(isset($_GET["m"]))
        {
            switch($_GET["m"])
            {
                case '1':
                ?>
                <h2 style="color:red;"> Usted no puede acceder al contenido del administrador </h2>
                <?php
                break;

                case '2':
                ?>
                <h2 style="color:red;"> Los datos están vacíos </h2>
                <?php
                break;

                case '3':
                ?>
                <h2 style="color:red;"> Solo puede subir archivos txt, doc, docx, ppt, pptx y pdf. </h2>
                <?php
                break;

                case '4':
                ?>
                <h2 style="color:red;"> El archivo no debe exceder los 6 Mb de capacidad. </h2>
                <?php
                break;

                case '5':
                ?>
                <h2 style="color:green;"> El archivo fue subido con &eacutexito. </h2>
                <?php
                break;

                case '6':
                ?>
                <h2 style="color:red;"> El t&iacutetulo del archivo ya existe. </h2>
                <?php
                break;
            }
        }
        ?>

        <table align="center" width="550">
        <td valign="middle" align="center" colspan="2" width="400">
        <hr>
        </td>

        <tr style="background-color:#FCAE4F">
        <td valign="middle" align="right" width="200">
        T&iacutetulo:
        </td>
        <td valign="middle" align="left" width="200">
        <input type="text" name="titulo" size ="40"/>
        </td>
        </tr>

        <tr style="background-color:#FCAE4F">
        <td valign="middle" align="right" width="200">
        Categoria:
        </td>
        <td valign="middle" align="left" width="200"><label>
        <select name="categoria" id="select">
            <option selected="selected">Elegir</option>
            <option>Programaci&oacuten</option>
            <option>Sistemas Expertos</option>
            <option>Entornos Virutales</option>
            <option>Evaluaci&oacuten de Sistemas </option>
            <option>Otros</option>
        </select>
        </label>
        </td>
        </tr>

        <tr style="background-color:#FCAE4F">
        <td valign="middle" align="right" width="200">
        Tu archivo:
        </td>
        <td valign="middle" align="left" width="200">
		<input type="file" name="archivo" /> <br>(Solo archivos doc, docx, pdf, ppt, pptx, txt)
        </td>
        </tr>

        <tr style="background-color:#FCAE4F">
        <td valign="middle" align="right" width="200">
        Descripci&oacuten:
        </td>
        <td valign="middle" align="left" width="200">
        <div id="textarea">
        <textarea name="descripcion" id="decripcion" cols="30" rows="3"></textarea></div>
        </td>
        </tr>

        <tr>
        <td valign="middle" align="center" colspan="2" width="400">
        <hr />
    	<input type="hidden" name="grabar" value="si" />
        <input type="button" value="subir" title="subir" onclick="document.form.submit();" />
        </td>
        </tr>
        </table>
        </form>
    </div>  <!--Fin div contenedor_medio-->
    <div id="reloj">
        <?php include("reloj.phtml"); ?>
    </div>
    <div id="sidebar">
        <?php include("perfilgral.phtml"); ?>
    </div>
    <div id="footer">
    <hr />
    &copy; Universidad Mayor de San Sim&oacuten - Entornos Virtuales  - <?php echo date("Y");?>
    </div>
</div> <!--Fin div Principal-->
</center>
</body>
</html>