<table width="820" height="440" align="center" border="2">
<td width="820" height="440" colspan="9" align="center" valign="top"> <span class="Estilo7">
      <object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=8,0,0,0" width="820" height="440" align="center">
        <param name="allowScriptAccess" value="sameDomain" />
        <param name="movie" value="images/tarzan.swf" />
        <param name="quality" value="high" />
        <param name="bgcolor" value="#EDEDED" />
        <param name="background" value="../images/fondo.png" />
        <embed src="images/tarzan.swf" width="820" height="440" align="center" quality="high" bgcolor= "" allowScriptAccess="sameDomain" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" />
      </object>
    </span> </td>

</table>